In [1]:
import pandas as pd

In [2]:
# Read in the output data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13491 entries, 0 to 13490
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   author                       13491 non-null  object
 1   deterministic_author         4339 non-null   object
 2   fuzzy_author                 5321 non-null   object
 3   fuzzy_author_score           13491 non-null  float64
 4   distilbert_author            13491 non-null  object
 5   distilbert_author_score      13491 non-null  float64
 6   title                        13491 non-null  object
 7   tokenized_title              13491 non-null  object
 8   matched_title_deterministic  13491 non-null  object
 9   matched_title_fuzzy          13491 non-null  object
 10  fuzzy_title_score            13491 non-null  float64
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [3]:
df.head()

,author,deterministic_author,fuzzy_author,fuzzy_author_score,distilbert_author,distilbert_author_score,title,tokenized_title,matched_title_deterministic,matched_title_fuzzy,fuzzy_title_score
0,"Du Creux, François, 1596?-1666.",NaN,NaN,0.0,"{'authorized_name': 'cruz, luís da, 1543-1604...",0.467436,"Historiæ canadensis, seu Novæ-Franciæ libri de...","['', 'canadendo', 'seu', 'novæ', '', 'decem', ...",Unknown,Unknown,0.0
1,"Meyer, Ernst H. F. 1791-1858.",NaN,NaN,0.0,"{'authorized_name': 'meyer, wilhelm, 1845-1917...",0.999939,Ernesti Meyer de plantis labradoricis libri tres.,"['ernestus', 'meyer', 'planta', 'labradoricus'...",Unknown,Unknown,0.0
2,"Laet, Joannes de, 1593-1649.",NaN,NaN,0.0,"{'authorized_name': 'larroumet, gustave', 'aut...",0.494394,"Novus orbis, seu Descriptionis Indiae Occident...","['nouus', 'orbis', 'siue', 'descriptio', 'indi...",Unknown,Unknown,0.0
3,"Caesar, Julius",NaN,"{'authorized_name': 'caesar, julius', 'author_...",1.0,"{'authorized_name': 'caesar, julius', 'author_...",0.999999,C. Julii Cæsaris commentariorum De Bello Galli...,"['julius', 'cæsar', 'commentarius', 'bellum', ...",Unknown,Unknown,0.0
4,Unknown,NaN,NaN,0.0,{'authorized_name': 'stephanus abbas 4. or 6th...,0.177454,Collectanea latina seu ecclesiasticæ antiquita...,"['collectaneum', 'latinus', 'siue', 'ecclesias...",Unknown,Unknown,0.0